### ISSUE TITLE
Server crashes on startup after updating to 1.15.0 (replication_rs2_bridge incompatible with refinedstorage 2.0.9?)

### ISSUE THREAD

**Issue by Pulz-TCP** [FTBTeam/FTB-Modpack-Issues#12359]
### Have you tried the solutions mentioned above? 

Yes

### Modpack

FTB StoneBlock 4

### Modpack Version

1.15.0

### Launcher/App used to start the modpack

Server

### Describe what happened

The server crashes immediately on every startup after updating from 1.14.2 to 1.15.0. The server never finishes loading, it dies on the first server tick. The crash did not occur on 1.14.2.

I see a `NoSuchMethodError` for `replication_rs2_bridge` 1.2.5 calling `TaskContainer.attachAll()`.

### Link to logs

https://mclo.gs/49ApHi2

### Steps to reproduce

1. Update existing server from 1.14.2 to 1.15.0
2. Crash

Fresh 1.15.0 server is unaffected.

### Has the pack been modified

Yes (Server side utility mods)

**Comment by LevyWilson** [comment]
Same thing. 

[crash-2026-06-13_16.19.39-server.txt](https://github.com/user-attachments/files/28915229/crash-2026-06-13_16.19.39-server.txt)

**Comment by LevyWilson** [comment]
Downgrading Refined Storage to 2.0.8 lets the server start, but obviously no clients can connect. Did no one even check to see if the replication bridge mod was compatible with 2.0.9? Who tested this update. Seriously?

**Comment by LevyWilson** [comment]
Posted my crashlog on the Replication RS2 Bridge github page to bring it to their attention. https://github.com/Leclowndu93150/Replication-RS2-Bridge/issues/3

**Comment by LevyWilson** [comment]
@Saereth @Traverse-Joe The bridge mod just updated to be compatible with 2.0.9. I see you guys downgraded to 2.0.8 for 1.15.2, but upgraded it to 2.0.9 for 1.15.3 before the replication bridge mod could update to be compatible with 2.0.9. Should I assume 1.15.3 has the same issue that 1.15.0 had and just wait for a 1.15.4 with the new replication bridge update?

**Comment by Pulz-TCP** [comment]
@LevyWilson I can confirm that it has been broken since 1.15 was released, so just under a week now.

**Comment by LevyWilson** [comment]
@Saereth @Traverse-Joe  Do we need to make another issue? Cus, like, Repli RS2 Bridge in SB4 1.15.3 is still not compatible with the 2.0.9 RS2. It was updated, but the update isn't in 1.15.3

**Comment by Pulz-TCP** [comment]
@LevyWilson Feel free to make a new issue - I'm likely pulling the pack from my community due to the downtime, so will probably not be able to contribute to any further discussion.

**Comment by LevyWilson** [comment]
@Pulz-TCP We just reverted to 1.14.2. though technically 1.15.2 fixes this and 1.15.3 re breaks it, so we could update to 1.15.2, but I figured a 1.15.4 would have been released by now...

**Comment by Gaz492** [comment]
Sorry, we don't monitor closed issues, so this got lost.

**Comment by Pulz-TCP** [comment]
My server has been offline for two weeks. I've had no choice but to close it permanently.

**Comment by LevyWilson** [comment]
The update to 1.16.0 seems to fix it. It updated the Replication Bridge mod at least.
